switches:
  main: [2, 3, 4]
  sw1: [5, 6, 7]
  sw2: [8, 9, 10]
leds:
  - {module: 1, pin: 0}
  - {module: 1, pin: 1}
  - {module: 1, pin: 2}
  - {module: 1, pin: 3}
  - {module: 1, pin: 4}
  - {module: 1, pin: 5}
  - {module: 1, pin: 6}
  - {module: 1, pin: 7}
  - {module: 1, pin: 8}
  - {module: 1, pin: 9}
  - {module: 1, pin: 10}
  - {module: 1, pin: 11}
  - {module: 1, pin: 12}
  - {module: 1, pin: 13}
  - {module: 1, pin: 14}
  - {module: 1, pin: 15}
  - {module: 2, pin: 0}
  - {module: 2, pin: 1}
  - {module: 2, pin: 2}
  - {module: 2, pin: 3}
  - {module: 2, pin: 4}
  - {module: 2, pin: 5}
states:
  - {main: 1, sw1: 0}
  - {main: 1, sw1: 1}
  - {main: 1, sw1: 2}
  - {main: 1, sw1: 3}
  - {main: 1, sw1: 4}
  - {main: 1, sw1: 5}
  - {main: 1, sw1: 6}
  - {main: 1, sw1: 7}
  - {main: 0, sw2: 0}
  - {main: 0, sw2: 1}
  - {main: 0, sw2: 2}
  - {main: 0, sw2: 3}
  - {main: 0, sw2: 4}
  - {main: 0, sw2: 5}
  - {main: 0, sw2: 6}
  - {main: 0, sw2: 7}
  - {main: 2}
  - {main: 3}
  - {main: 4}
  - {main: 5}
  - {main: 6}
  - {main: 7}
